### ISSUE TITLE
API key leak detected

### ISSUE THREAD

**Issue by jzvikart** [Sifchain/sa-eliza#117]
In current `ai16z/develop` somebody is printing the entire HTTP request to OpenAI, revealing API key in `Authorization: Bearer` header.

We should warn about such cases everybody who's merging PRs. This was specifically one of the cases we warned about. The key should be considered compromised.

**Comment by jzvikart** [comment]
Fixed, PR pending

**Comment by jkbrooks** [comment]
@jzvikart would you link to the PR that fixes this?

**Comment by jzvikart** [comment]
Fixed here: https://github.com/elizaOS/eliza/pull/1177
