### ISSUE TITLE
Privately turn on test run in CI/CD and file tickets on whatever breaks

### ISSUE THREAD

**Issue by snobbee** [Sifchain/sa-eliza#13]
> Privately turn on test run in CI/CD and file tickets on whatever breaks

**Comment by pgoos** [comment]
Seems like 3 tests are broken. I'll file tickets for them

**Comment by pgoos** [comment]
New PR created: https://github.com/ai16z/eliza/pull/590 - all tests are passing now.

**Comment by jkbrooks** [comment]
Okay so @pgoos should we consider this ticket done?  If so, please close if not please explain why
