### ISSUE TITLE
Set up a framework for integration testing

### ISSUE THREAD

**Issue by TimKozak** [Sifchain/sa-eliza#91]
Preparing a set of functions that would enable us to create and manage creation of integration tests for plugin, adapter, client & agent folders.

Provide building blocks for anyone who is doing integration tests for Eliza.

**Comment by jzvikart** [comment]
Initial implementation is complete. The framework in this version takes care of setting up a working environment in which integration tests can run. The first integration test ("hello Trump") uses this framework to send a message to the agent.
